# =========================
# 应用程序配置 Application Configuration
# =========================

# =========================
# 服务器配置
# =========================
[server]
# HTTP API 服务器地址端口配置
host = "127.0.0.1"
port = 8080
# UNIX socket 路径 (用于 parser-proxy 通信)
unix_socket_path = "/tmp/parser_proxy.sock"

# =========================
# Solana 区块链配置
# =========================
[solana]
# RPC 节点地址
rpc_url = "https://api.mainnet-beta.solana.com"
# 支付账户私钥 (建议通过环境变量 PAYER_PRIVATE_KEY 设置)
payer_private_key = ""

# =========================
# SWQOS (Solana Web Quality of Service) 配置
# 用于选择交易提交的质量服务提供商
# =========================
[swqos]
# 服务区域选择: NewYork | Frankfurt | Amsterdam | Tokyo | SLC | London | LosAngeles | Default
region = "NewYork"

# 启用的服务提供商列表
[[swqos.enabled_providers]]
provider = "Astralane"
api_token = ""
enabled = false

[[swqos.enabled_providers]]
provider = "BlockRazor"
api_token = ""
enabled = false

[[swqos.enabled_providers]]
provider = "Jito"
api_token = ""  # JITO_UUID
enabled = false

[[swqos.enabled_providers]]
provider = "NextBlock"
api_token = ""  # NEXTBLOCK_API_TOKEN
enabled = false

[[swqos.enabled_providers]]
provider = "Bloxroute"
api_token = ""  # BLOXROUTE_API_TOKEN
enabled = false

[[swqos.enabled_providers]]
provider = "ZeroSlot"
api_token = ""
enabled = false

[[swqos.enabled_providers]]
provider = "Temporal"
api_token = ""
enabled = false

[[swqos.enabled_providers]]
provider = "FlashBlock"
api_token = ""  # FLASHBLOCK_API_TOKEN
enabled = false

[[swqos.enabled_providers]]
provider = "Node1"
api_token = ""  # NODE1_API_TOKEN
enabled = false

[[swqos.enabled_providers]]
provider = "Default"
api_token = ""
enabled = false

# =========================
# gRPC 客户端配置
# =========================
[grpc]
# Yellowstone gRPC 端点地址
endpoint = "https://solana-yellowstone-grpc.publicnode.com:443"
# gRPC 认证 Token (可选)
token = ""
# 启用性能指标
enable_metrics = true
# 启用 TLS
enable_tls = true
# 连接超时 (毫秒)
connection_timeout_ms = 10000
# 请求超时 (毫秒)
request_timeout_ms = 30000

# =========================
# DEX 协议配置
# =========================
[protocols]
# 启用要监听的 DEX 协议
pumpfun = true
pumpswap = false
meteora_damm_v2 = false

# =========================
# 事件过滤配置
# =========================
[events]
# PumpFun 协议事件
pumpfun_trade = true
pumpfun_create = true
pumpfun_migrate = true

# PumpSwap 协议事件
pumpswap_buy = false
pumpswap_sell = false
pumpswap_create_pool = false
pumpswap_liquidity_added = false
pumpswap_liquidity_removed = false

# Meteora DAMM V2 协议事件
meteora_damm_v2_swap = false
meteora_damm_v2_add_liquidity = false
meteora_damm_v2_remove_liquidity = false
meteora_damm_v2_create_position = false
meteora_damm_v2_close_position = false
